/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  augus
 * Created: 20/02/2019
 */
SET DATABASE SQL SYNTAX PGS TRUE;
SET DATABASE SQL SIZE FALSE;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS MEETUP;
DROP TABLE IF EXISTS NOTIFICACION;
DROP TABLE IF EXISTS USUARIO_MEETUP;

CREATE TABLE USUARIO (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR NOT NULL,
    TIPO_USUARIO VARCHAR NOT NULL
);

CREATE TABLE MEETUP (
    ID SERIAL PRIMARY KEY,
    FECHA_INICIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP NOT NULL
);

CREATE TABLE NOTIFICACION (
    ID SERIAL PRIMARY KEY,
    MENSAJE VARCHAR NOT NULL
);

CREATE TABLE USUARIO_MEETUP (
    USUARIO_ID INTEGER NOT NULL,
    MEETUP_ID INTEGER NOT NULL,
    FECHA_CHECK_IN TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (USUARIO_ID, MEETUP_ID)
);

-- CREATE TABLE USUARIO_MEETUP_KEY (
--     USUARIO_ID INTEGER NOT NULL,
--     MEETUP_ID INTEGER NOT NULL,
--     CONSTRAINT FK_USUARIO_ID FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
--     CONSTRAINT FK_MEETUP_ID FOREIGN KEY (MEETUP_ID) REFERENCES MEETUP(ID)
-- )

