/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  augus
 * Created: 20/02/2019
 */
DROP TABLE IF EXISTS NOTIFICACION;
DROP TABLE IF EXISTS USUARIO_MEETUP;
DROP TABLE IF EXISTS MEETUP;
DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    TIPO_USUARIO VARCHAR(30) NOT NULL
);

CREATE TABLE MEETUP (
    ID SERIAL PRIMARY KEY,
    FECHA_INICIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE NOTIFICACION (
    ID SERIAL PRIMARY KEY,
    USUARIO_ID INTEGER NOT NULL,
    MEETUP_ID INTEGER NOT NULL,
    MENSAJE VARCHAR(300) NOT NULL,
    FECHA_LEIDO TIMESTAMP DEFAULT NULL
);

CREATE TABLE USUARIO_MEETUP (
    USUARIO_ID INTEGER NOT NULL,
    MEETUP_ID INTEGER NOT NULL,
    FECHA_CHECK_IN TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (USUARIO_ID, MEETUP_ID)
);

